#!/bin/bash
mysql --user="starraid" --password="12345" --database="starraid" --execute="DROP TABLE user_role;"
mysql --user="starraid" --password="12345" --database="starraid" --execute="DROP TABLE spaceship;"
mysql --user="starraid" --password="12345" --database="starraid" --execute="DROP TABLE user;"
mysql --user="starraid" --password="12345" --database="starraid" --execute="DROP TABLE role;"
mysql --user="starraid" --password="12345" --database="starraid" --execute="DELETE FROM phinxlog;"

./phinx migrate
./phinx seed:run -s RoleSeed
./phinx seed:run -s UserSeed
./phinx seed:run -s UserRoleSeed
./phinx seed:run -s SpaceshipSeed
